version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Generate Docker files
          command: ./run.sh

      - run:
          name: Commit them to images branch
          command: |
            git checkout images
            git add images
            git commit -m "update images"
            git push
